/**
 * Executable CLI script generator for generated workflows (Node.js & Bash runner).
 */

function sanitizeFilename(title) {
  return (
    String(title || 'workflow')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 60) || 'workflow'
  );
}

/**
 * @param {object} workflow assembled workflow
 * @returns {string} Executable Node.js CLI script content
 */
export function toScript(workflow) {
  if (!workflow || !Array.isArray(workflow.stages) || workflow.stages.length === 0) {
    throw new Error('Workflow has no stages to export');
  }

  const title = String(workflow.title || 'Workflow').replace(/'/g, "\\'");
  const summary = String(workflow.summary || '').replace(/'/g, "\\'");

  const stageCode = workflow.stages.map((stage, idx) => {
    const toolName = String(stage.tool?.name || stage.toolSlug || 'Tool').replace(/'/g, "\\'");
    const stageTitle = String(stage.title || toolName).replace(/'/g, "\\'");
    const website = String(stage.tool?.websiteUrl || '').replace(/'/g, "\\'");
    const steps = (stage.steps || []).map(s => String(s.title || s).replace(/'/g, "\\'"));
    const prompt = String(stage.prompt || '').replace(/`/g, '\\`');

    return `  {
    number: ${idx + 1},
    title: '${stageTitle}',
    tool: '${toolName}',
    website: '${website}',
    steps: ${JSON.stringify(steps)},
    prompt: \`${prompt}\`
  }`;
  }).join(',\n');

  return `#!/usr/bin/env node

/**
 * Executable Workflow Runner for: ${title}
 * Generated by AI Tools Workflow Studio
 */

const stages = [
${stageCode}
];

console.log('\\n======================================================');
console.log('🚀 Workflow: ${title}');
if ('${summary}') console.log('📝 Summary: ${summary}');
console.log('======================================================\\n');

async function run() {
  for (const stage of stages) {
    console.log(\`\\n--- [Stage \${stage.number}/\${stages.length}] \${stage.title} ---\`);
    console.log(\`🛠️  Tool: \${stage.tool}\${stage.website ? ' (' + stage.website + ')' : ''}\`);
    
    if (stage.steps && stage.steps.length) {
      console.log('📋 Steps to complete:');
      stage.steps.forEach((step, i) => console.log(\`   \${i + 1}. \${step}\`));
    }
    
    if (stage.prompt) {
      console.log('\\n💬 Recommended Prompt:');
      console.log('------------------------------------------------------');
      console.log(stage.prompt);
      console.log('------------------------------------------------------');
    }
    
    console.log(\`\\n✅ Stage \${stage.number} ready.\\n\`);
  }

  console.log('\\n🎉 Workflow Execution Guide Completed!\\n');
}

run().catch(console.error);
`;
}

export function scriptFilename(workflow) {
  return `${sanitizeFilename(workflow?.title)}-runner.js`;
}

export default { toScript, scriptFilename };
