import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import config from './config/index.js';
import { User, Tool, Comment, Category } from './models/index.js';

// Categories seed data
const categories = [
  { name: 'Writing', slug: 'writing', icon: '✍️', color: '#3b82f6', description: 'AI tools for writing, content creation, and text generation', order: 1 },
  { name: 'Image', slug: 'image', icon: '🖼️', color: '#8b5cf6', description: 'AI tools for image generation, editing, and manipulation', order: 2 },
  { name: 'Video', slug: 'video', icon: '🎬', color: '#06b6d4', description: 'AI tools for video creation, editing, and enhancement', order: 3 },
  { name: 'Audio', slug: 'audio', icon: '🎵', color: '#10b981', description: 'AI tools for audio, music, and voice generation', order: 4 },
  { name: 'Coding', slug: 'coding', icon: '💻', color: '#f59e0b', description: 'AI tools for programming, code generation, and development', order: 5 },
  { name: 'Productivity', slug: 'productivity', icon: '⚡', color: '#6366f1', description: 'AI tools for productivity, automation, and workflow', order: 6 },
  { name: 'Marketing', slug: 'marketing', icon: '📈', color: '#ec4899', description: 'AI tools for marketing, advertising, and growth', order: 7 },
  { name: 'Research', slug: 'research', icon: '🔬', color: '#14b8a6', description: 'AI tools for research, analysis, and knowledge discovery', order: 8 },
  { name: 'Design', slug: 'design', icon: '🎨', color: '#a855f7', description: 'AI tools for design, UI/UX, and creative work', order: 9 },
  { name: 'Business', slug: 'business', icon: '💼', color: '#f97316', description: 'AI tools for business operations and management', order: 10 },
  { name: 'Education', slug: 'education', icon: '📚', color: '#22c55e', description: 'AI tools for learning, teaching, and education', order: 11 },
  { name: 'Data & Analytics', slug: 'data', icon: '📊', color: '#0ea5e9', description: 'AI tools for data analysis, visualization, and insights', order: 12 },
  { name: 'Customer Support', slug: 'support', icon: '💬', color: '#f43f5e', description: 'AI tools for customer service and support', order: 13 },
  { name: 'HR & Recruiting', slug: 'hr', icon: '👥', color: '#8b5cf6', description: 'AI tools for human resources and recruiting', order: 14 },
  { name: 'Legal', slug: 'legal', icon: '⚖️', color: '#64748b', description: 'AI tools for legal research and document analysis', order: 15 },
  { name: 'Finance', slug: 'finance', icon: '💰', color: '#22c55e', description: 'AI tools for finance, accounting, and investments', order: 16 },
  { name: 'Healthcare', slug: 'healthcare', icon: '🏥', color: '#ef4444', description: 'AI tools for healthcare and medical applications', order: 17 },
  { name: 'E-commerce', slug: 'ecommerce', icon: '🛒', color: '#f59e0b', description: 'AI tools for e-commerce and online retail', order: 18 },
  { name: 'Social Media', slug: 'social', icon: '📱', color: '#3b82f6', description: 'AI tools for social media management and content', order: 19 },
  { name: 'Other', slug: 'other', icon: '🔧', color: '#64748b', description: 'Other AI tools and utilities', order: 100 },
];

// Seed data
const users = [
  {
    name: 'Admin User',
    email: 'admin@aitools.com',
    password: 'admin123',
    role: 'admin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
  },
  {
    name: 'John Doe',
    email: 'john@example.com',
    password: 'user123',
    role: 'user',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=john',
  },
  {
    name: 'Jane Smith',
    email: 'jane@example.com',
    password: 'user123',
    role: 'user',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jane',
  },
];

const tools = [
  // AI Assistants & Chatbots
  {
    name: 'ChatGPT',
    tagline: 'Advanced AI assistant for conversations, writing, and problem-solving',
    description: 'ChatGPT is an AI-powered language model developed by OpenAI. It can engage in conversational dialogue, answer questions, assist with writing tasks, help with coding, and much more.',
    logo: 'https://static.vecteezy.com/system/resources/previews/021/608/790/non_2x/chatgpt-logo-chat-gpt-icon-on-black-background-free-vector.jpg',
    screenshot: '/images/featured/chatgpt.png',
    websiteUrl: 'https://chat.openai.com',
    category: 'writing',
    pricing: 'freemium',
    pricingDetails: 'Free tier available. ChatGPT Plus at $20/month',
    features: ['Conversational AI', 'Code assistance', 'Writing help', 'Language translation', 'Image understanding'],
    tags: ['ai', 'chatbot', 'writing', 'coding', 'assistant'],
    views: 1250000,
    likes: 45000,
    rating: 4.8,
    reviewCount: 12500,
    isFeatured: true,
    isVerified: true,
  },
  {
    name: 'ChatGPT Plugins',
    tagline: 'Extend ChatGPT capabilities with powerful plugins',
    description: 'ChatGPT Plugins allow you to connect ChatGPT to third-party applications and services, enabling browsing, code execution, and access to real-time data.',
    logo: 'https://static.vecteezy.com/system/resources/previews/021/608/796/non_2x/chatgpt-logo-chat-gpt-app-icon-on-green-background-free-vector.jpg',
    screenshot: '/images/featured/chatgpt.png',
    websiteUrl: 'https://chat.openai.com',
    category: 'productivity',
    pricing: 'paid',
    pricingDetails: 'Requires ChatGPT Plus at $20/month',
    features: ['Web browsing', 'Code interpreter', 'Third-party integrations', 'Real-time data', 'Custom actions'],
    tags: ['ai', 'chatbot', 'plugins', 'productivity', 'integrations'],
    views: 850000,
    likes: 32000,
    rating: 4.6,
    reviewCount: 8200,
    isFeatured: true,
    isVerified: true,
  },
  {
    name: 'Claude',
    tagline: 'A helpful, harmless, and honest AI assistant',
    description: 'Claude is an AI assistant created by Anthropic. It excels at thoughtful dialogue, content creation, complex reasoning, and detailed analysis.',
    logo: 'https://media.licdn.com/dms/image/v2/D4E0BAQFko-zWIZk_pw/company-logo_200_200/B4EZhiRWKvHgAI-/0/1753995371543/claude_logo?e=2147483647&v=beta&t=CVNmFKyWig0Uo78oAr3II6KVLu_o0aXPtnt4S6XgOr8',
    screenshot: '/images/featured/claude.webp',
    websiteUrl: 'https://claude.ai',
    category: 'writing',
    pricing: 'freemium',
    pricingDetails: 'Free tier available. Claude Pro at $20/month',
    features: ['Long context window', 'Document analysis', 'Coding help', 'Creative writing', 'Research assistance'],
    tags: ['ai', 'chatbot', 'writing', 'assistant', 'anthropic'],
    views: 580000,
    likes: 24000,
    rating: 4.7,
    reviewCount: 4800,
    isFeatured: true,
    isVerified: true,
  },
  {
    name: 'Google Gemini',
    tagline: 'Google\'s most capable AI model for multimodal understanding',
    description: 'Google Gemini is a multimodal AI model that can understand and generate text, code, images, audio, and video. It powers Google\'s AI products and services.',
    logo: 'https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/dark/gemini-color.png',
    screenshot: 'https://picsum.photos/seed/gemini/800/600',
    websiteUrl: 'https://gemini.google.com',
    category: 'writing',
    pricing: 'freemium',
    pricingDetails: 'Free tier available. Gemini Advanced at $19.99/month',
    features: ['Multimodal AI', 'Code generation', 'Image understanding', 'Long context', 'Google integration'],
    tags: ['ai', 'chatbot', 'multimodal', 'google', 'assistant'],
    views: 920000,
    likes: 38000,
    rating: 4.7,
    reviewCount: 9500,
    isFeatured: true,
    isVerified: true,
  },
  {
    name: 'Perplexity AI',
    tagline: 'AI-powered answer engine for research',
    description: 'Perplexity AI is an AI-powered search engine that provides direct answers to questions with cited sources.',
    logo: 'https://framerusercontent.com/images/gcMkPKyj2RX8EOEja8A1GWvCb7E.jpg',
    screenshot: 'https://picsum.photos/seed/tool138/800/600',
    websiteUrl: 'https://perplexity.ai',
    category: 'research',
    pricing: 'freemium',
    pricingDetails: 'Free tier available. Pro at $20/month',
    features: ['Real-time search', 'Source citations', 'Follow-up questions', 'File analysis', 'Collections'],
    tags: ['ai', 'search', 'research', 'knowledge', 'assistant'],
    views: 410000,
    likes: 17000,
    rating: 4.6,
    reviewCount: 3100,
    isFeatured: true,
    isVerified: true,
  },
  {
    name: 'Komo Search',
    tagline: 'AI-powered search engine with conversational interface',
    description: 'Komo Search is an AI search engine that provides fast, ad-free answers with a focus on privacy and user experience.',
    logo: 'https://komo.ai/icon.svg',
    screenshot: 'https://picsum.photos/seed/tool157/800/600',
    websiteUrl: 'https://komo.ai',
    category: 'research',
    pricing: 'free',
    pricingDetails: 'Free to use',
    features: ['AI search', 'Ad-free', 'Privacy focused', 'Quick answers', 'Clean interface'],
    tags: ['ai', 'search', 'research', 'privacy', 'free'],
    views: 120000,
    likes: 5500,
    rating: 4.3,
    reviewCount: 890,
    isFeatured: false,
    isVerified: true,
  },

  // Coding & Development
  {
    name: 'GitHub Copilot',
    tagline: 'Your AI pair programmer that helps you write code faster',
    description: 'GitHub Copilot is an AI-powered code completion tool developed by GitHub in collaboration with OpenAI.',
    logo: 'https://pnghdpro.com/wp-content/themes/pnghdpro/download/social-media-and-brands/github-copilot-logo-icon-hd.png',
    screenshot: 'https://picsum.photos/seed/tool178/800/600',
    websiteUrl: 'https://github.com/features/copilot',
    category: 'coding',
    pricing: 'paid',
    pricingDetails: '$10/month for individuals, $19/month for business',
    features: ['Code suggestions', 'Multi-language support', 'IDE integration', 'Natural language to code', 'Test generation'],
    tags: ['ai', 'coding', 'programming', 'developer tools', 'github'],
    views: 750000,
    likes: 32000,
    rating: 4.7,
    reviewCount: 7200,
    isFeatured: true,
    isVerified: true,
  },
  {
    name: 'Claude Code',
    tagline: 'AI-powered coding assistant by Anthropic',
    description: 'Claude Code is an agentic coding tool from Anthropic that can understand your codebase, write code, fix bugs, and help with complex programming tasks.',
    logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZleuSWjfZGUB_aCncoBFE8v4stq1HGLcNdg&s',
    screenshot: 'https://picsum.photos/seed/tool197/800/600',
    websiteUrl: 'https://claude.ai',
    category: 'coding',
    pricing: 'paid',
    pricingDetails: 'Included with Claude Pro at $20/month',
    features: ['Code generation', 'Bug fixing', 'Code review', 'Refactoring', 'Multi-language support'],
    tags: ['ai', 'coding', 'programming', 'anthropic', 'developer tools'],
    views: 320000,
    likes: 14000,
    rating: 4.6,
    reviewCount: 2800,
    isFeatured: true,
    isVerified: true,
  },
  {
    name: 'Cursor',
    tagline: 'The AI-first code editor built for pair programming',
    description: 'Cursor is an AI-powered code editor that helps you write, edit, and understand code faster with intelligent suggestions and natural language commands.',
    logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrQ_CU3a6muH84mLfoP6xmM4ZJ9Z6RAXMmdA&s',
    screenshot: 'https://picsum.photos/seed/tool216/800/600',
    websiteUrl: 'https://cursor.sh',
    category: 'coding',
    pricing: 'freemium',
    pricingDetails: 'Free tier available. Pro at $20/month',
    features: ['AI code completion', 'Natural language editing', 'Codebase understanding', 'Multi-file editing', 'Chat interface'],
    tags: ['ai', 'coding', 'editor', 'ide', 'developer tools'],
    views: 480000,
    likes: 22000,
    rating: 4.8,
    reviewCount: 4200,
    isFeatured: true,
    isVerified: true,
  },
  {
    name: 'Tabnine',
    tagline: 'AI code assistant that runs on your machine',
    description: 'Tabnine is an AI code completion tool that learns from your codebase to provide relevant suggestions while keeping your code private.',
    logo: 'https://pbs.twimg.com/profile_images/1785337827787726848/6UeBPcDU_400x400.png',
    screenshot: 'https://picsum.photos/seed/tool235/800/600',
    websiteUrl: 'https://tabnine.com',
    category: 'coding',
    pricing: 'freemium',
    pricingDetails: 'Free tier available. Pro at $12/month',
    features: ['Code completion', 'Local processing', 'Privacy focused', 'Multi-IDE support', 'Team learning'],
    tags: ['ai', 'coding', 'autocomplete', 'privacy', 'developer tools'],
    views: 280000,
    likes: 11000,
    rating: 4.4,
    reviewCount: 2100,
    isFeatured: false,
    isVerified: true,
  },
  {
    name: 'Qodo',
    tagline: 'AI-powered code integrity and testing platform',
    description: 'Qodo (formerly CodiumAI) helps developers write better code with AI-generated tests, code analysis, and intelligent suggestions.',
    logo: 'https://avatars.githubusercontent.com/u/183290039?s=200&v=4',
    screenshot: 'https://picsum.photos/seed/tool254/800/600',
    websiteUrl: 'https://qodo.ai',
    category: 'coding',
    pricing: 'freemium',
    pricingDetails: 'Free tier available. Pro plans for teams',
    features: ['Test generation', 'Code analysis', 'PR review', 'Code suggestions', 'IDE integration'],
    tags: ['ai', 'coding', 'testing', 'code quality', 'developer tools'],
    views: 95000,
    likes: 4200,
    rating: 4.5,
    reviewCount: 780,
    isFeatured: false,
    isVerified: true,
  },

  // Image Generation
  {
    name: 'Midjourney',
    tagline: 'Create stunning AI-generated artwork from text descriptions',
    description: 'Midjourney is an independent research lab that produces an AI program that creates images from textual descriptions.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/2/24/Midjourney_Emblem.svg',
    screenshot: '/images/featured/midjourney.jpg',
    websiteUrl: 'https://midjourney.com',
    category: 'image',
    pricing: 'paid',
    pricingDetails: 'Plans starting at $10/month',
    features: ['Text-to-image', 'Style customization', 'High resolution', 'Variations', 'Upscaling'],
    tags: ['ai', 'art', 'image generation', 'creative', 'design'],
    views: 980000,
    likes: 38000,
    rating: 4.9,
    reviewCount: 8900,
    isFeatured: true,
    isVerified: true,
  },
  {
    name: 'DALL·E',
    tagline: 'Create realistic images and art from natural language descriptions',
    description: 'DALL·E is OpenAI\'s image generation model that creates images from text descriptions with unprecedented accuracy and creativity.',
    logo: 'https://miro.medium.com/1*EAPcBv5ndN73E7YP-gjebA.png',
    screenshot: '/images/featured/dalle-3.png',
    websiteUrl: 'https://openai.com/dall-e-3',
    category: 'image',
    pricing: 'paid',
    pricingDetails: 'Available through ChatGPT Plus ($20/month) or API',
    features: ['Text-to-image', 'High accuracy', 'Built-in safety', 'Aspect ratio control', 'Style variety'],
    tags: ['ai', 'image generation', 'art', 'creative', 'openai'],
    views: 620000,
    likes: 28000,
    rating: 4.8,
    reviewCount: 5400,
    isFeatured: true,
    isVerified: true,
  },
  {
    name: 'Adobe Firefly',
    tagline: 'Generative AI made for creators by Adobe',
    description: 'Adobe Firefly is a family of creative generative AI models designed to generate images, vectors, videos, and 3D content safely for commercial use.',
    logo: 'https://designcompass.org/wp-content/uploads/2025/07/firefly-mobile-07-1536x1152.jpg',
    screenshot: 'https://picsum.photos/seed/tool313/800/600',
    websiteUrl: 'https://firefly.adobe.com',
    category: 'image',
    pricing: 'freemium',
    pricingDetails: 'Free tier available. Premium with Creative Cloud subscription',
    features: ['Text-to-image', 'Generative fill', 'Text effects', 'Commercial safe', 'Adobe integration'],
    tags: ['ai', 'image generation', 'adobe', 'creative', 'design'],
    views: 520000,
    likes: 21000,
    rating: 4.6,
    reviewCount: 4100,
    isFeatured: true,
    isVerified: true,
  },
  {
    name: 'Leonardo AI',
    tagline: 'Create production-quality visual assets with AI',
    description: 'Leonardo AI is an AI art generator that allows you to create stunning game assets, concept art, and images with unprecedented quality and control.',
    logo: 'https://play-lh.googleusercontent.com/AqrK5WNAGhCVqoaCsViNHAECb3Jzvll84cmPmmzFFrsq7hayVMrTdhinoW5pyTkh1MaC',
    screenshot: 'https://picsum.photos/seed/tool332/800/600',
    websiteUrl: 'https://leonardo.ai',
    category: 'image',
    pricing: 'freemium',
    pricingDetails: 'Free tier with 150 tokens/day. Pro at $12/month',
    features: ['Image generation', 'Fine-tuned models', 'Canvas editor', 'Image guidance', 'Community models'],
    tags: ['ai', 'image generation', 'art', 'game assets', 'creative'],
    views: 380000,
    likes: 16000,
    rating: 4.7,
    reviewCount: 3200,
    isFeatured: false,
    isVerified: true,
  },
  {
    name: 'Stable Diffusion',
    tagline: 'Open-source AI image generation model',
    description: 'Stable Diffusion is an open-source deep learning text-to-image model that can generate detailed images based on text descriptions.',
    logo: 'https://sc.filehippo.net/images/t_app-icon-l/p/f0e339f0-7f93-44bf-994d-37c547df3d9f/2658909461/stable-diffusion-online-out%20(2).png',
    screenshot: 'https://picsum.photos/seed/tool351/800/600',
    websiteUrl: 'https://stability.ai',
    category: 'image',
    pricing: 'free',
    pricingDetails: 'Open source. Cloud services available',
    features: ['Text-to-image', 'Open source', 'Local deployment', 'Fine-tuning', 'Community models'],
    tags: ['ai', 'image generation', 'open source', 'creative', 'art'],
    views: 720000,
    likes: 31000,
    rating: 4.5,
    reviewCount: 6800,
    isFeatured: false,
    isVerified: true,
  },

  // Video Generation
  {
    name: 'Runway',
    tagline: 'Create videos with AI magic tools',
    description: 'Runway is a creative toolkit that uses AI to make video editing and creation accessible to everyone with powerful generative AI tools.',
    logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrrw3CqAv94IBxZ6QIIfqXL4hRRID8p4EQoA&s',
    screenshot: 'https://picsum.photos/seed/tool372/800/600',
    websiteUrl: 'https://runway.ml',
    category: 'video',
    pricing: 'freemium',
    pricingDetails: 'Free tier with limited credits. Pro starts at $15/month',
    features: ['Text-to-video', 'Image-to-video', 'Video editing', 'Green screen', 'Motion tracking'],
    tags: ['ai', 'video', 'editing', 'creative', 'generation'],
    views: 380000,
    likes: 16000,
    rating: 4.6,
    reviewCount: 2900,
    isFeatured: true,
    isVerified: true,
  },
  {
    name: 'Synthesia',
    tagline: 'Create AI videos with virtual presenters',
    description: 'Synthesia is an AI video generation platform that lets you create professional videos with AI avatars speaking your script in multiple languages.',
    logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzKm7Y_m5XL7F_DLG8y-gdJdmNoYIe4Yg5Dw&s',
    screenshot: 'https://picsum.photos/seed/tool391/800/600',
    websiteUrl: 'https://synthesia.io',
    category: 'video',
    pricing: 'paid',
    pricingDetails: 'Personal at $22/month, Business plans available',
    features: ['AI avatars', 'Multi-language', 'Script to video', 'Custom avatars', 'Templates'],
    tags: ['ai', 'video', 'avatars', 'presentations', 'training'],
    views: 290000,
    likes: 12000,
    rating: 4.5,
    reviewCount: 2300,
    isFeatured: true,
    isVerified: true,
  },  {
    name: 'TubeBlink',
    tagline: 'Optimize YouTube videos with AI-powered SEO',
    description: 'TubeBlink is an AI-powered YouTube optimization tool that helps creators analyze video performance, improve SEO, generate engaging titles and descriptions, and boost channel growth.',
    logo: 'https://picsum.photos/seed/tubeblink-logo/400/400',
    screenshot: 'https://picsum.photos/seed/tubeblink/800/600',
    websiteUrl: 'https://tubeblink.com',
    category: 'marketing',
    pricing: 'freemium',
    pricingDetails: 'Free tier available. Pro starts at $19/month',
    features: ['SEO optimization', 'Title generator', 'Thumbnail analyzer', 'Performance analytics', 'Competitor insights'],
    tags: ['ai', 'youtube', 'seo', 'video', 'marketing', 'analytics'],
    views: 85000,
    likes: 3200,
    rating: 4.3,
    reviewCount: 420,
    isFeatured: false,
    isVerified: true,
  },  {
    name: 'DomoAI',
    tagline: 'Transform videos and images with AI animation',
    description: 'DomoAI is an AI creative tool that transforms videos and images into stunning animations and different art styles.',
    logo: 'https://media.licdn.com/dms/image/v2/D560BAQGzfknHjeAltA/company-logo_200_200/company-logo_200_200/0/1716185055693/domoai_pte_ltd_logo?e=2147483647&v=beta&t=EPa-yKskW25Ixu1l58Q7BN7GkQmpRVLEMNdEfrrbVYc',
    screenshot: 'https://picsum.photos/seed/tool410/800/600',
    websiteUrl: 'https://domoai.app',
    category: 'video',
    pricing: 'freemium',
    pricingDetails: 'Free tier available. Pro plans starting at $9.99/month',
    features: ['Video-to-animation', 'Style transfer', 'Image animation', 'Multiple styles', 'Discord bot'],
    tags: ['ai', 'video', 'animation', 'art style', 'creative'],
    views: 145000,
    likes: 6800,
    rating: 4.4,
    reviewCount: 1200,
    isFeatured: false,
    isVerified: true,
  },
  {
    name: 'Hypernatural',
    tagline: 'AI-powered video creation for social media',
    description: 'Hypernatural helps you create engaging video content for social media using AI, making video production fast and effortless.',
    logo: 'https://play-lh.googleusercontent.com/bFz9VelAjOKO28-BoMKMVV1U2KXBe4U4zMa7PR8rd_Enfh8XPZ-fMB-BXVOuRzbAX_sQ=w240-h480-rw',
    screenshot: 'https://picsum.photos/seed/tool429/800/600',
    websiteUrl: 'https://hypernatural.ai',
    category: 'video',
    pricing: 'freemium',
    pricingDetails: 'Free tier available. Pro plans for creators',
    features: ['AI video creation', 'Social media optimization', 'Quick editing', 'Templates', 'Auto-captions'],
    tags: ['ai', 'video', 'social media', 'content creation', 'marketing'],
    views: 78000,
    likes: 3200,
    rating: 4.3,
    reviewCount: 540,
    isFeatured: false,
    isVerified: true,
  },
  {
    name: 'RecCloud',
    tagline: 'AI-powered video recording and editing platform',
    description: 'RecCloud is an online video platform with AI features for recording, editing, and enhancing videos with automatic transcription and translation.',
    logo: 'https://play-lh.googleusercontent.com/ZPj9rngiNXll2dLtxEnsmRg-sMCJxrrcy7WZvMOb2LKTekZvEBHMiHFLp6OZJxFIfEY',
    screenshot: 'https://picsum.photos/seed/tool448/800/600',
    websiteUrl: 'https://reccloud.com',
    category: 'video',
    pricing: 'freemium',
    pricingDetails: 'Free tier available. Premium at $9.99/month',
    features: ['Screen recording', 'AI transcription', 'Video editing', 'Auto-translation', 'Cloud storage'],
    tags: ['ai', 'video', 'recording', 'transcription', 'editing'],
    views: 65000,
    likes: 2800,
    rating: 4.2,
    reviewCount: 480,
    isFeatured: false,
    isVerified: true,
  },

  // Writing & Content
  {
    name: 'Jasper',
    tagline: 'AI writing assistant for marketing teams',
    description: 'Jasper is an AI writing platform designed for marketing teams. It helps create blog posts, social media content, ads, emails, and more.',
    logo: 'https://cdn-public.softwarereviews.com/production/favicons/offerings/11476/original/heyjasperai_logo.png',
    screenshot: 'https://picsum.photos/seed/tool469/800/600',
    websiteUrl: 'https://jasper.ai',
    category: 'marketing',
    pricing: 'paid',
    pricingDetails: 'Creator at $49/month, Teams at $125/month',
    features: ['Content templates', 'Brand voice', 'SEO optimization', 'Team collaboration', 'Chrome extension'],
    tags: ['ai', 'writing', 'marketing', 'content', 'copywriting'],
    views: 290000,
    likes: 12000,
    rating: 4.4,
    reviewCount: 2100,
    isFeatured: true,
    isVerified: true,
  },
  {
    name: 'Copy.ai',
    tagline: 'AI-powered copywriting and content generation',
    description: 'Copy.ai is an AI copywriter that generates high-quality copy for your business, including ads, emails, social media posts, and more.',
    logo: 'https://pbs.twimg.com/profile_images/1882909654545551360/QPAmppjU_400x400.jpg',
    screenshot: 'https://picsum.photos/seed/tool488/800/600',
    websiteUrl: 'https://copy.ai',
    category: 'marketing',
    pricing: 'freemium',
    pricingDetails: 'Free tier available. Pro at $49/month',
    features: ['Copywriting', 'Blog posts', 'Ad copy', 'Email copy', 'Social media content'],
    tags: ['ai', 'writing', 'copywriting', 'marketing', 'content'],
    views: 320000,
    likes: 13500,
    rating: 4.4,
    reviewCount: 2400,
    isFeatured: false,
    isVerified: true,
  },
  {
    name: 'Writesonic',
    tagline: 'AI writing tool for creating SEO-optimized content',
    description: 'Writesonic is an AI writing assistant that creates SEO-optimized content, including articles, blog posts, ads, and product descriptions.',
    logo: 'https://plgdemos.com/content/images/2024/05/writesonic.svg',
    screenshot: 'https://picsum.photos/seed/tool507/800/600',
    websiteUrl: 'https://writesonic.com',
    category: 'writing',
    pricing: 'freemium',
    pricingDetails: 'Free tier available. Pro starts at $16/month',
    features: ['Article writing', 'SEO optimization', 'AI chatbot', 'Paraphrasing', 'Multi-language'],
    tags: ['ai', 'writing', 'seo', 'content', 'marketing'],
    views: 245000,
    likes: 10000,
    rating: 4.3,
    reviewCount: 1800,
    isFeatured: false,
    isVerified: true,
  },
  {
    name: 'Grammarly',
    tagline: 'AI-powered writing assistant for clear communication',
    description: 'Grammarly is an AI-powered writing assistant that helps you write clear, mistake-free content with grammar, spelling, and style suggestions.',
    logo: 'https://play-lh.googleusercontent.com/6Xe9DWiMC76daosOC80Im9gqe25Q9P55LxJIGPTLbcdFkMXOur4mk8jTVxoqOaiAvAG4',
    screenshot: 'https://picsum.photos/seed/tool526/800/600',
    websiteUrl: 'https://grammarly.com',
    category: 'writing',
    pricing: 'freemium',
    pricingDetails: 'Free basic features. Premium at $12/month',
    features: ['Grammar checking', 'Tone detection', 'Clarity suggestions', 'Plagiarism detection', 'Browser extension'],
    tags: ['ai', 'writing', 'grammar', 'editing', 'productivity'],
    views: 680000,
    likes: 28000,
    rating: 4.6,
    reviewCount: 5800,
    isFeatured: true,
    isVerified: true,
  },
  {
    name: 'Otter.ai',
    tagline: 'AI-powered meeting transcription and notes',
    description: 'Otter.ai is an AI meeting assistant that transcribes meetings in real-time, captures slides, generates summaries, and allows you to chat with your meetings.',
    logo: 'https://cdn.prod.website-files.com/63b9c43cf803b0331540fa68/67ef9e76a9bd9b3e47900153_otter.ai%20logo.png',
    screenshot: 'https://picsum.photos/seed/tool545/800/600',
    websiteUrl: 'https://otter.ai',
    category: 'productivity',
    pricing: 'freemium',
    pricingDetails: 'Free tier with 300 minutes/month. Pro at $16.99/month',
    features: ['Real-time transcription', 'Meeting summaries', 'Speaker identification', 'Keyword highlights', 'Integrations'],
    tags: ['ai', 'transcription', 'meetings', 'productivity', 'notes'],
    views: 420000,
    likes: 18000,
    rating: 4.5,
    reviewCount: 3600,
    isFeatured: false,
    isVerified: true,
  },

  // Productivity & Workspace
  {
    name: 'Notion AI',
    tagline: 'AI-powered writing assistant integrated into your workspace',
    description: 'Notion AI helps you write, brainstorm, edit, summarize, and more. It\'s seamlessly integrated into Notion workspace.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png',
    screenshot: 'https://picsum.photos/seed/tool566/800/600',
    websiteUrl: 'https://notion.so/product/ai',
    category: 'productivity',
    pricing: 'paid',
    pricingDetails: '$10/month add-on to any Notion plan',
    features: ['Writing assistance', 'Summarization', 'Translation', 'Action items', 'Q&A'],
    tags: ['ai', 'productivity', 'writing', 'workspace', 'notes'],
    views: 420000,
    likes: 18000,
    rating: 4.5,
    reviewCount: 3600,
    isFeatured: true,
    isVerified: true,
  },
  {
    name: 'Zapier AI',
    tagline: 'Automate workflows with AI-powered automation',
    description: 'Zapier AI helps you create automated workflows using natural language, connecting thousands of apps with intelligent automation.',
    logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrVwOzVey6XcMevohRDman3xgDFw91v8qZfw&s',
    screenshot: 'https://picsum.photos/seed/tool585/800/600',
    websiteUrl: 'https://zapier.com/ai',
    category: 'productivity',
    pricing: 'freemium',
    pricingDetails: 'Free tier available. Pro starts at $19.99/month',
    features: ['Natural language automation', 'App integrations', 'AI actions', 'Workflow builder', 'Chatbots'],
    tags: ['ai', 'automation', 'productivity', 'integrations', 'workflow'],
    views: 380000,
    likes: 15000,
    rating: 4.5,
    reviewCount: 3100,
    isFeatured: false,
    isVerified: true,
  },
  {
    name: 'Gamma',
    tagline: 'AI-powered presentations and documents',
    description: 'Gamma is an AI tool that creates beautiful presentations, documents, and webpages in seconds. Just describe what you need and Gamma generates it.',
    logo: 'https://store-images.s-microsoft.com/image/apps.53673.13800228740496758.b926c1b0-f31a-4a9b-b1b3-88dd15f27137.a0a38389-643f-48ed-9379-92a9fb5a7c94',
    screenshot: 'https://picsum.photos/seed/tool604/800/600',
    websiteUrl: 'https://gamma.app',
    category: 'productivity',
    pricing: 'freemium',
    pricingDetails: 'Free tier available. Plus at $10/month',
    features: ['AI presentations', 'Document generation', 'Templates', 'Collaboration', 'Export options'],
    tags: ['ai', 'presentations', 'documents', 'productivity', 'design'],
    views: 310000,
    likes: 13000,
    rating: 4.6,
    reviewCount: 2700,
    isFeatured: true,
    isVerified: true,
  },
  {
    name: 'Tome',
    tagline: 'AI-powered storytelling and presentations',
    description: 'Tome is an AI-native format for presentations and storytelling. Create compelling narratives with AI-generated content and visuals.',
    logo: 'https://images.saasworthy.com/pptai_50802_logo_1744623159_ugyv2.png',
    screenshot: 'https://picsum.photos/seed/tool623/800/600',
    websiteUrl: 'https://tome.app',
    category: 'productivity',
    pricing: 'freemium',
    pricingDetails: 'Free tier available. Pro at $16/month',
    features: ['AI storytelling', 'Presentations', 'Image generation', 'Templates', 'Collaboration'],
    tags: ['ai', 'presentations', 'storytelling', 'productivity', 'creative'],
    views: 260000,
    likes: 11000,
    rating: 4.4,
    reviewCount: 2200,
    isFeatured: false,
    isVerified: true,
  },
  {
    name: 'Beautiful.ai',
    tagline: 'AI-powered presentation software',
    description: 'Beautiful.ai is a presentation software that uses AI to automatically design slides, making it easy to create professional presentations.',
    logo: 'https://image.pngaaa.com/677/5527677-middle.png',
    screenshot: 'https://picsum.photos/seed/tool642/800/600',
    websiteUrl: 'https://beautiful.ai',
    category: 'design',
    pricing: 'paid',
    pricingDetails: 'Pro at $12/month, Team at $40/user/month',
    features: ['Smart templates', 'Auto-design', 'Team collaboration', 'Analytics', 'Export options'],
    tags: ['ai', 'presentations', 'design', 'productivity', 'business'],
    views: 185000,
    likes: 7800,
    rating: 4.4,
    reviewCount: 1400,
    isFeatured: false,
    isVerified: true,
  },
  {
    name: 'DeckRobot',
    tagline: 'AI-powered PowerPoint automation',
    description: 'DeckRobot uses AI to automatically format and design PowerPoint presentations according to your brand guidelines.',
    logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRhBqjyt82OqTlKi12vqr5dU3PWFumhrg0XQ&s',
    screenshot: 'https://picsum.photos/seed/tool661/800/600',
    websiteUrl: 'https://deckrobot.com',
    category: 'productivity',
    pricing: 'paid',
    pricingDetails: 'Contact for pricing',
    features: ['Auto-formatting', 'Brand compliance', 'PowerPoint integration', 'Slide library', 'Team templates'],
    tags: ['ai', 'presentations', 'powerpoint', 'automation', 'business'],
    views: 45000,
    likes: 2100,
    rating: 4.2,
    reviewCount: 380,
    isFeatured: false,
    isVerified: true,
  },
  {
    name: 'Visme',
    tagline: 'AI-powered visual content creation platform',
    description: 'Visme is an all-in-one visual content platform that helps you create presentations, infographics, documents, and more with AI assistance.',
    logo: 'https://play-lh.googleusercontent.com/QZdNXGnTzyUkESFKC0wYlXWEFlePUgabIi3ZZgqLdpK9BNV-bVlvkt8ly5i7Vsj-QAY',
    screenshot: 'https://picsum.photos/seed/tool680/800/600',
    websiteUrl: 'https://visme.co',
    category: 'design',
    pricing: 'freemium',
    pricingDetails: 'Free tier available. Pro at $12.25/month',
    features: ['Presentations', 'Infographics', 'AI design assistant', 'Brand kit', 'Templates'],
    tags: ['ai', 'design', 'presentations', 'infographics', 'visual content'],
    views: 210000,
    likes: 9000,
    rating: 4.4,
    reviewCount: 1650,
    isFeatured: false,
    isVerified: true,
  },

  // Education & Learning
  {
    name: 'Khanmigo',
    tagline: 'AI-powered tutor by Khan Academy',
    description: 'Khanmigo is an AI tutoring assistant from Khan Academy that helps students learn by guiding them through problems without giving away answers.',
    logo: 'https://e7.pngegg.com/pngimages/847/994/png-clipart-khan-academy-logo-thumbnail-tech-companies.png',
    screenshot: 'https://picsum.photos/seed/tool701/800/600',
    websiteUrl: 'https://khanacademy.org/khan-labs',
    category: 'education',
    pricing: 'paid',
    pricingDetails: '$44/year for individuals, district pricing for schools',
    features: ['AI tutoring', 'Personalized learning', 'Writing coach', 'Math help', 'Safe for students'],
    tags: ['ai', 'education', 'tutoring', 'learning', 'students'],
    views: 280000,
    likes: 12000,
    rating: 4.7,
    reviewCount: 2400,
    isFeatured: true,
    isVerified: true,
  },
  {
    name: 'Quizlet',
    tagline: 'AI-powered study tools and flashcards',
    description: 'Quizlet uses AI to help students study more effectively with smart flashcards, practice tests, and personalized study paths.',
    logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbkFwnOkTIBpePBpDUWgVJjyCBYDR9sR3jUQ&s',
    screenshot: 'https://picsum.photos/seed/tool720/800/600',
    websiteUrl: 'https://quizlet.com',
    category: 'education',
    pricing: 'freemium',
    pricingDetails: 'Free tier available. Plus at $35.99/year',
    features: ['Flashcards', 'Practice tests', 'Learn mode', 'AI tutor', 'Study sets'],
    tags: ['ai', 'education', 'flashcards', 'studying', 'learning'],
    views: 520000,
    likes: 22000,
    rating: 4.5,
    reviewCount: 4800,
    isFeatured: false,
    isVerified: true,
  },

  // Resume & Career
  {
    name: 'Kickresume',
    tagline: 'AI resume and cover letter builder',
    description: 'Kickresume helps you create professional resumes and cover letters with AI writing assistance and beautiful templates.',
    logo: 'https://play-lh.googleusercontent.com/bVCcspE4dwHfX9ebtj9aUU7ZXNGSSFl6Sxje8JSckAQp1b_WL3qhjPQz3hvPGB_e0Kmo',
    screenshot: 'https://picsum.photos/seed/tool741/800/600',
    websiteUrl: 'https://kickresume.com',
    category: 'hr',
    pricing: 'freemium',
    pricingDetails: 'Free tier available. Premium at $19/month',
    features: ['AI resume writer', 'Cover letters', 'Templates', 'ATS optimization', 'Website builder'],
    tags: ['ai', 'resume', 'career', 'job search', 'hr'],
    views: 180000,
    likes: 7500,
    rating: 4.4,
    reviewCount: 1400,
    isFeatured: false,
    isVerified: true,
  },
  {
    name: 'Enhancv',
    tagline: 'AI-powered resume builder for job seekers',
    description: 'Enhancv uses AI to help you build resumes that stand out, with personalized suggestions and professional templates.',
    logo: 'https://cdn.dribbble.com/userupload/17423380/file/original-44ab547f301834f39d3caba7df9c9b30.jpg?resize=752x&vertical=center',
    screenshot: 'https://picsum.photos/seed/tool760/800/600',
    websiteUrl: 'https://enhancv.com',
    category: 'hr',
    pricing: 'freemium',
    pricingDetails: 'Free tier available. Pro at $24.99/month',
    features: ['AI content suggestions', 'Templates', 'Real-time feedback', 'ATS friendly', 'LinkedIn import'],
    tags: ['ai', 'resume', 'career', 'job search', 'professional'],
    views: 145000,
    likes: 6200,
    rating: 4.5,
    reviewCount: 1150,
    isFeatured: false,
    isVerified: true,
  },
  {
    name: 'VMock',
    tagline: 'AI-powered career coaching platform',
    description: 'VMock provides AI-powered career guidance with instant resume feedback, interview preparation, and personalized career advice.',
    logo: 'https://play-lh.googleusercontent.com/jIuZc_NxClrJfozI47IEwnonNQFqUD77o5-tDKXhmxUDIx8JJpaOJFD5SCx6JIv0Wqk=w240-h480-rw',
    screenshot: 'https://picsum.photos/seed/tool779/800/600',
    websiteUrl: 'https://vmock.com',
    category: 'hr',
    pricing: 'paid',
    pricingDetails: 'Available through universities or direct subscription',
    features: ['Resume scoring', 'Instant feedback', 'Interview prep', 'Career advice', 'LinkedIn optimization'],
    tags: ['ai', 'career', 'resume', 'coaching', 'professional'],
    views: 95000,
    likes: 4100,
    rating: 4.3,
    reviewCount: 720,
    isFeatured: false,
    isVerified: true,
  },

  // E-commerce & Shopping
  {
    name: 'Google Shopping',
    tagline: 'AI-powered shopping search and comparison',
    description: 'Google Shopping uses AI to help you find and compare products across the web, with price tracking and personalized recommendations.',
    logo: 'https://w7.pngwing.com/pngs/217/427/png-transparent-google-shopping-tag-logo-icon.png',
    screenshot: 'https://picsum.photos/seed/tool800/800/600',
    websiteUrl: 'https://shopping.google.com',
    category: 'ecommerce',
    pricing: 'free',
    pricingDetails: 'Free to use',
    features: ['Product search', 'Price comparison', 'Price tracking', 'Reviews', 'Local availability'],
    tags: ['ai', 'shopping', 'ecommerce', 'price comparison', 'google'],
    views: 890000,
    likes: 35000,
    rating: 4.4,
    reviewCount: 7200,
    isFeatured: false,
    isVerified: true,
  },
  {
    name: 'DealSpotr',
    tagline: 'AI-powered deals and coupon platform',
    description: 'DealSpotr uses AI to find and verify the best deals, coupons, and discounts from thousands of retailers.',
    logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZXEPHTn_IUTAwoWvlwskYuV9LEOKfLl9jKQ&s',
    screenshot: 'https://picsum.photos/seed/tool819/800/600',
    websiteUrl: 'https://dealspotr.com',
    category: 'ecommerce',
    pricing: 'free',
    pricingDetails: 'Free to use',
    features: ['Deal aggregation', 'Coupon verification', 'Price tracking', 'Community ratings', 'Browser extension'],
    tags: ['ai', 'shopping', 'coupons', 'deals', 'savings'],
    views: 120000,
    likes: 5200,
    rating: 4.2,
    reviewCount: 890,
    isFeatured: false,
    isVerified: true,
  },
];

const comments = [
  {
    content: 'ChatGPT has completely transformed how I work. The ability to brainstorm ideas, draft content, and even debug code is incredible. Highly recommended!',
    rating: 5,
  },
  {
    content: 'Great tool but can sometimes give incorrect information. Always verify important facts. Otherwise, very useful for day-to-day tasks.',
    rating: 4,
  },
  {
    content: 'The free version is quite limited but the Plus subscription is worth every penny. The GPT-4 model is significantly better.',
    rating: 4,
  },
];

async function seed() {
  try {
    console.log('Connecting to MongoDB...');
    await mongoose.connect(config.mongoUri);
    console.log('Connected to MongoDB');
    
    // Clear existing data
    console.log('Clearing existing data...');
    await Promise.all([
      User.deleteMany({}),
      Tool.deleteMany({}),
      Comment.deleteMany({}),
      Category.deleteMany({}),
    ]);
    
    // Create categories
    console.log('Creating categories...');
    const createdCategories = [];
    for (const categoryData of categories) {
      const category = new Category(categoryData);
      await category.save();
      createdCategories.push(category);
    }
    console.log(`Created ${createdCategories.length} categories`);
    
    // Create users
    console.log('Creating users...');
    const createdUsers = [];
    for (const userData of users) {
      const user = new User(userData);
      await user.save();
      createdUsers.push(user);
    }
    console.log(`Created ${createdUsers.length} users`);
    
    const adminUser = createdUsers.find(u => u.role === 'admin');
    
    // Create tools
    console.log('Creating tools...');
    const createdTools = [];
    for (const toolData of tools) {
      const tool = new Tool({
        ...toolData,
        createdBy: adminUser._id,
      });
      await tool.save();
      createdTools.push(tool);
    }
    console.log(`Created ${createdTools.length} tools`);
    
    // Create comments for the first tool (ChatGPT)
    console.log('Creating comments...');
    const chatgpt = createdTools.find(t => t.name === 'ChatGPT');
    const regularUsers = createdUsers.filter(u => u.role === 'user');
    
    for (let i = 0; i < comments.length; i++) {
      const comment = new Comment({
        ...comments[i],
        tool: chatgpt._id,
        user: regularUsers[i % regularUsers.length]._id,
      });
      await comment.save();
    }
    console.log(`Created ${comments.length} comments`);
    
    console.log('\n✅ Seed completed successfully!\n');
    console.log('Test accounts:');
    console.log('  Admin: admin@aitools.com / admin123');
    console.log('  User: john@example.com / user123');
    console.log('  User: jane@example.com / user123\n');
    
    await mongoose.connection.close();
    process.exit(0);
  } catch (error) {
    console.error('Seed failed:', error);
    process.exit(1);
  }
}

seed();

